spring:
  security:
    oauth2:
      client:
        provider:
          myclient:
            issuer-uri: "http://localhost:9000"
        registration:
          myclient:
            client-id: "demoClientId"
            client-secret: "demoClientSecret"
            authorization-grant-type: "client_credentials"
            scope: openid
  sleuth:
    web:
      webclient:
        enabled: true
